const images = {
  logo: require("@/assests/images/Group 215.svg").default,
  img1: require("@/assests/images/Rectangle1.svg").default,
  imgDoc1: require("@/assests/images/Rectangle 22.svg").default,
  doctor : require("@/assests/images/doctor.png").default,
  doctor1 : require("@/assests/images/doctor1.svg").default,
  doctor2 : require("@/assests/images/doctor2.svg").default,
  doctor3 : require("@/assests/images/doctor3.svg").default,
  doctor4 : require("@/assests/images/doctor4.svg").default,
  whyus1 : require("@/assests/images/WhyUs-icon1.svg").default,
  whyus2 : require("@/assests/images/WhyUs-icon2.svg").default,
  whyus3 : require("@/assests/images/WhyUs-icon3.svg").default,
  whyus4 : require("@/assests/images/WhyUs-icon4.svg").default,
  whyus5 : require("@/assests/images/WhyUs-icon5.svg").default,
  whyus6 : require("@/assests/images/WhyUs-icon6.svg").default,
  img39: require("@/assests/images/Rectangle 39.png"),
  img5: require("@/assests/images/Rectangle 5.svg").default,
  img6: require("@/assests/images/Rectangle 6.svg").default,
  img40: require("@/assests/images/Rectangle 40.svg").default,
  img41: require("@/assests/images/Rectangle 41.svg").default,
  calendar: require("@/assests/images/Calendar.png"),
  location: require("@/assests/images/Location.png"),
  aboutus: require("@/assests/images/AboutUs.png"),
  C1: require("@/assests/images/C1.png"),
  C2: require("@/assests/images/C2.png"),
  C3: require("@/assests/images/C3.png"),
};

export default images;
